### ISSUE TITLE
IFC Version NOT required 

### ISSUE THREAD

**Issue by cicciopage** [CBenghi/ids-tool#1]
The tool requires that "ifcVersion" attribute inside "Specification" node is mandatory.
According to XSD, the "ifcVersion" attribute must be present but it could be empty.
Example:

1)
`<ids:specification ifcVersion=""
		                   name="Spec 1"
		                   minOccurs="1"
		                   maxOccurs="1">
			<ids:applicability/>
			<ids:requirements/>
		</ids:specification>`

2)
`<ids:specification ifcVersion="IFC2X3 IFC4 IFC4X3"
		                   name="Spec 2"
		                   minOccurs="1"
		                   maxOccurs="unbounded">
			<ids:applicability/>
			<ids:requirements/>
		</ids:specification>`

XSD:
`<xs:attribute name="ifcVersion" use="required">
			<xs:simpleType>
				<xs:list>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="IFC2X3"/>
							<xs:enumeration value="IFC4"/>
							<xs:enumeration value="IFC4X3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:list>
			</xs:simpleType>
		</xs:attribute>`

**Comment by CBenghi** [comment]
This repository is only retained as a placeholer.

The current version of the tool is hosted at: https://github.com/buildingSMART/IDS-Audit-tool
