### ISSUE TITLE
symbol for decimal number 

### ISSUE THREAD

**Issue by cicciopage** [CBenghi/ids-tool#2]
According to XSD, decimal number must have dot (.) symbol to separate the whole number from its fractional parts.
If the symbol is comma (,), (like european format), the tool must return an error.

Example:
Right: 12.3    45.45    67.444
Error: 12,3    45,45    67,444

**Comment by CBenghi** [comment]
This repository is only retained as a placeholer.

The current version of the tool is hosted at: https://github.com/buildingSMART/IDS-Audit-tool
